### ISSUE TITLE
Who We Are: Who We Are posts should have menu ordering

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Independent-Valuers#22]

**Comment by bernardtitan** [comment]
The order of items is reversed, higher order attributes should be displayed later than ones with lower order attributes

**Comment by bernardtitan** [comment]
Menu ordering has been implemented, but items with a higher order attribute should be displayed later than items with lower order attributes

**Comment by rexcebudigital** [comment]
I did not change anything, Its already order by menu_order, you can see the last post is Test 3 only which contains menu order: 1 and the rest is 0.

**Comment by bernardtitan** [comment]
Regardless, test 1, test 2 and test 4 are more recent than the Information coming soon posts. 

The expected behavior should go like this:

If we have five items (a, b, c, d, e) which are uploaded in order they will all have the order attribute 0, in which case they will be displayed as follows:

e
d
c
b
a

Because 'e' was uploaded last, it is displayed first. This is a basic aspect of menu ordering, wherein if the order attributes are the same, it should function more or less identically to order by date.

We then change the order attribute of 'c' to 3 and 'b' to 2. The order should then be:

e
d
a
b
c

This is because the lower order attributes have higher priority than higher ones.
