### ISSUE TITLE
Request a Quote: The form fields are too small in IE

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Independent-Valuers#40]

**Comment by rexcebudigital** [comment]
Can I ask a screenshot for this cause on my end its fine and readable.

**Comment by bernardtitan** [comment]
It's not about readability, it's the size of the fields in comparison to other browsers
![request a quote - 01](https://cloud.githubusercontent.com/assets/11186359/6865518/6554e948-d4a9-11e4-9a80-b8f0c9f5f3e5.jpg)
