### ISSUE TITLE
Header - Main Menu: Submenus are broken in IE8 and IE7

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Independent-Valuers#67]

**Comment by bernardtitan** [comment]
Submenus are still broken in IE8

**Comment by bernardtitan** [comment]
![header - 01](https://cloud.githubusercontent.com/assets/11186359/6910788/62d6c518-d78a-11e4-89ca-0bcd0ce79cdd.jpg)

**Comment by rexcebudigital** [comment]
Here's my IE8 and IE7 screenshot
![ie8](https://cloud.githubusercontent.com/assets/11186391/6913233/f957334a-d7af-11e4-87a1-ecf1a4ae5c61.jpg)
![ie7](https://cloud.githubusercontent.com/assets/11186391/6913234/f958e37a-d7af-11e4-9cf6-1cb2633f932b.jpg)
