### ISSUE TITLE
Homepage: The repeater should refer the list with checkmarks beside the picture of the man. The services section should list items from the 'What We Can Do' page

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Independent-Valuers#9]
Reading the design brief, it states that the 'What We Can Do' page should list all services and describe them in more detail. 

It also makes more sense, from a logical perspective to explain in detail the services moreso than one-line marketing blurbs.

**Comment by rexcebudigital** [comment]
By basing on the design. The check-marks title beside the man is the same with the post title of What we can do page. Is this a design error?

**Comment by bernardtitan** [comment]
Yes, the check marks beside the man might be done as a repeater in a global custom field as it also appears in the sidebar.
