### ISSUE TITLE
Homepage: There are extra bullets in the service list in the mobile site

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Independent-Valuers#90]

**Comment by bernardtitan** [comment]
![home - 07](https://cloud.githubusercontent.com/assets/11186359/6933089/59a6d318-d855-11e4-84dd-80c9fb139309.png)

**Comment by rexcebudigital** [comment]
I have checked through googlechrome emulator using the stage link. I dont see the bug on my end.
