### ISSUE TITLE
Homepage: The text under the banner isn't displayed on the iPad

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Independent-Valuers#92]

**Comment by rexcebudigital** [comment]
Can I ask a screenshot for this please? Thank you.

**Comment by bernardtitan** [comment]
![home - 05](https://cloud.githubusercontent.com/assets/11186359/6932957/c7765be0-d853-11e4-902c-3629ddd0c7b6.jpg)

**Comment by rexcebudigital** [comment]
I dont see the bug on my end using chrome emulator
